version: '3.8'

services:
  web:
    build: ./backend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:10000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "10000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ai_resume_analyzer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123456
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: